experimenter: JohnDoe
subject_metadata:
  species: 'mouse'
  genotype: ['PV-Cre', 'VIP-Cre', 'SST-Cre']

rig_config:
  Laptop:
    data_directory: /home/johndoe/Desktop
    screen_center: [0, 0]
    rig: (testing)
    server_options: {'use_server': False,
                     #'disp_server_id': [1,0], # Use if you need to specify a particular display server and id.
                     'visual_stim_module_paths': ['/home/dennis/vanilla_labpack/labpack/visual_stim']}

# Note - default server address is '0.0.0.0' port 60629
  Other:
    data_directory: /home/johndoe/Desktop
    screen_center: [0, 0]
    rig: example_server 
    server_options: {'host': '0.0.0.0',
                     'port': 60629,
                     'use_server': True,
                     'visual_stim_module_paths': []}

# To use non-default stimpack functions, set them here
parameter_presets_dir: presets/example  # directory where your parameter presets live

module_paths:  # relative to the labpack directory specified in stimpack.experiment's path_to_labpack.txt
  protocol: labpack/protocol/JohnDoe_protocol.py  # module for user protocol classes. Should include class name "BaseProtocol"
  data: labpack/data.py  # module for data class. Class name should be "Data"
  client: labpack/client.py  # module for client class. Class name should be "Client"
  daq: labpack/device/daq.py  # daq module
